services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: money_tracker_mongodb_server
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: moneytracker
  #   networks:
  #     - my-network
  #   healthcheck:
  #     test: ["CMD-SHELL", "nc -z localhost 27017"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5

  server:
    build: ./server
    image: money_tracker_server:v1
    container_name: money_tracker_server_c1
    ports:
      - '5001:5001'
    volumes:
      - ./server:/app
      - /app/node_modules
#     env_file: ./server/.env
#     environment:
#       - JWT_SECRET_KEY=SECRETJWTTOKENGENERATIONKEY
#       - DB_URL=mongodb://mongodb:27017/moneytracker
#       - PORT=5001
#     depends_on:
#       mongodb:
#         condition: service_healthy
#     command: npm start
#     networks:
#       - my-network

# networks:
#   my-network:
#     driver: bridge
